In [1]:
# Importing the numpy library
import numpy as np

# 2D array
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

# Getting a specific element => 10
print(f"{a[0, 9]} => is at a specific position")

# Getting a specific row
print(f"This is the first row in the numpy array 'a' => {a[0, :]}")

# Getting a specific row
print(f"This is the second row in the numpy array 'a' => {a[1, :]}")

# Getting a specific column
print(f"This is the first column in the numpy array 'a' => {a[:, 0]}")

# Getting a specific column
print(f"This is the second column in the numpy array 'a' => {a[:, 1]}")

# Fancy indexing (starting index : ending index : step size)
# Example to get elements (2,4,6) from the array
print(f"To get the elements (2, 4, 6) from 'a', we use a[0, 1:6:2] => {a[0, 1:6:2]}")

# Changing an element in a column
a[:, 5] = [21, 22]
print(f"Changing column 5 to [21, 22] => \n{a}")
print("\n\n")

# 3D Example
b = np.array([
    [[1, 2, 3],
     [4, 5, 6],  # Layer 0
     [7, 8, 9]],
    
    [[10, 11, 12],  # Layer 1
     [13, 14, 14], 
     [15, 16, 17]]
])
print("This is a 3D array:")
print(b)

# Getting a specific element in a 3D array
# Syntax: [i, j, k] (layer, row, column)
print(f"The element at layer 0, row 1, column 1 => {b[0, 1, 1]}")

# Printing elements in a specific row (layer 1, row 0)
print(f"These are elements from layer 1, row 0 => {b[1, 0, :]}")
print(f"These are elements from layer 1, column 0 => {b[1, :, 0]}")

# Replacing elements in a 3D array
b[:, 1, :] = 9
print(f"Replacing all elements in the middle row of all layers with 9 => \n{b}")


10 => is at a specific position
This is the first row in the numpy array 'a' => [ 1  2  3  4  5  6  7  8  9 10]
This is the second row in the numpy array 'a' => [11 12 13 14 15 16 17 18 19 20]
This is the first column in the numpy array 'a' => [ 1 11]
This is the second column in the numpy array 'a' => [ 2 12]
To get the elements (2, 4, 6) from 'a', we use a[0, 1:6:2] => [2 4 6]
Changing column 5 to [21, 22] => 
[[ 1  2  3  4  5 21  7  8  9 10]
 [11 12 13 14 15 22 17 18 19 20]]



This is a 3D array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 14]
  [15 16 17]]]
The element at layer 0, row 1, column 1 => 5
These are elements from layer 1, row 0 => [10 11 12]
These are elements from layer 1, column 0 => [10 13 15]
Replacing all elements in the middle row of all layers with 9 => 
[[[ 1  2  3]
  [ 9  9  9]
  [ 7  8  9]]

 [[10 11 12]
  [ 9  9  9]
  [15 16 17]]]
